# Rôle central
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=120000

# Pour l'instant, on désactive le backlight pour éviter les erreurs de devicetree
# CONFIG_ZMK_BACKLIGHT=y
# CONFIG_ZMK_BACKLIGHT_BRT_START=100
# CONFIG_ZMK_BACKLIGHT_ON_START=y
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
