include:
  - board: xiao_ble//zmk
    shield: ergonaut_one_left
  - board: xiao_ble//zmk
    shield: ergonaut_one_right
  - board: xiao_ble//zmk
    shield: ergonaut_one_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_left_studio
  - board: xiao_ble//zmk
    shield: ergonaut_one_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_right_studio
  - board: xiao_ble//zmk
    shield: settings_reset
  # Dongle : empilement des deux shields.
  # ergonaut_one_dongle EN PREMIER (il définit le label &st7789
  # que l'overlay de prospector_adapter référence), puis
  # prospector_adapter qui apporte le code et la config Prospector.
  - board: nice_nano@2.0.0//zmk
    shield: ergonaut_one_dongle prospector_adapter
  - board: nice_nano@2.0.0//zmk
    shield: ergonaut_one_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_dongle_studio
