# Configuration du Dongle ZMK (Active le rôle BLE central)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Activation de l'affichage spécifique à ZMK
CONFIG_DISPLAY=y
CONFIG_ZMK_DISPLAY=y

# Activation du rétroéclairage ZMK
CONFIG_PWM=y
CONFIG_LED=y
CONFIG_LED_PWM=y
CONFIG_ZMK_BACKLIGHT=y

# Correctif pour le symbole MIPI DBI manquant
CONFIG_COMPILER_OPT="-DDT_N_S_soc_S_spi_40004000_S_st7789_0_P_mipi_mode_STRING_UPPER_TOKEN=MIPI_DBI_MODE_SPI_4WIRE"
