# Configuration du Dongle ZMK (Rôle BLE central)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Activation de l'affichage et du rétroéclairage
CONFIG_DISPLAY=y
CONFIG_PWM=y
CONFIG_LED=y
CONFIG_LED_PWM=y

# Désactivation des capteurs non présents
CONFIG_SENSOR=n
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
