# Configuration du Dongle ZMK (Active le rôle BLE central)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Activation de l'affichage spécifique à ZMK
CONFIG_DISPLAY=y
CONFIG_ZMK_DISPLAY=y

# Activation du rétroéclairage simple (sans PWM)
CONFIG_LED=y
CONFIG_ZMK_BACKLIGHT=y

# Correctif pour l'écran SPI
CONFIG_COMPILER_OPT="-DDT_N_S_soc_S_spi_40004000_S_st7789_0_P_mipi_mode_STRING_UPPER_TOKEN=MIPI_DBI_MODE_SPI_4WIRE"
CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
