# ==========================================
# 1. ACTIVATION DU MATÉRIEL
# ==========================================
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_ZMK_DISPLAY=y

# ==========================================
# 2. CONFIGURATION MÉMOIRE & GRAPHIQUE (LVGL)
# ==========================================
CONFIG_LV_Z_VDB_SIZE=50
CONFIG_LV_Z_MEM_POOL_SIZE=10000
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=8192

# Composants graphiques valides
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_BAR=y
CONFIG_LV_USE_LINE=y
CONFIG_LV_USE_FLEX=y

# ==========================================
# 3. CONFIGURATION PROSPECTOR
# ==========================================
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=y
# CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=y
