# ==========================================
# 1. ACTIVATION DU MATÉRIEL (OBLIGATOIRE)
# ==========================================
# Active la communication SPI pour envoyer les données à l'écran
CONFIG_SPI=y
# Active le sous-système d'affichage de Zephyr
CONFIG_DISPLAY=y
# Active la gestion des écrans par ZMK
CONFIG_ZMK_DISPLAY=y

# ==========================================
# 2. CONFIGURATION PROSPECTOR
# ==========================================
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# Désactiver le capteur de lumière ambiante
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n

# Luminosité fixe (1 à 100)
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80

# Mettre les noms de calques en majuscules
CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=y

# Rotation à 180° si nécessaire (décommente si besoin)
# CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=y
