# ==========================================
# CONFIGURATION DU SPLIT (Périphériques)
# ==========================================
CONFIG_ZMK_SPLIT=y

# Gestion de l'alimentation et veille
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=1800

# Bluetooth et USB pour les moitiés
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
