manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ergonautkb
      url-base: https://github.com/ergonautkb
    - name: snake-dongle           # <--- AJOUT
      url-base: https://github.com/joaopedropio/snake-dongle  # <--- AJOUT
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: ergonautkb-zmk-module
      remote: ergonautkb
      revision: main
    - name: snake-module           # <--- AJOUT
      remote: snake-dongle        # <--- AJOUT
      revision: zephyr-4.1         # <--- AJOUT (car ZMK est en main)
  self:
    path: config
